# name : "Deploy the script"

# on: 
#  push:
#   branches: 
#    - main
#    - develop

# jobs:
#   build-and-upload:
#     runs-on: ubuntu-latest


#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v4

#       - name: Setup Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: 22
      
#       - name: Install dependencies
#         run: npm install